version: "3.9"

services:

  # media server
  plex:
    env_file: .env
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=$UID
      - PGID=$GID
      - VERSION=docker
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - ./plex/library:/config
      - $SHARED_MEDIA_LOCATION:/data
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  # TV show finder, indexer
  sonarr:
    env_file: .env
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=Africa/Johannesburg
    volumes:
      - ./sonarr/config:/config
      - $SHARED_MEDIA_LOCATION:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  # Movie finder, indexer
  radarr:
    env_file: .env
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=Africa/Johannesburg
    volumes:
      - ./radarr/config:/config
      - $SHARED_MEDIA_LOCATION:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  # torrent client
  transmission:
    env_file: .env
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    volumes:
      - ./transmission/config:/config
      - $SHARED_MEDIA_LOCATION:/data
    environment:
      - TZ=Africa/Johannesburg
      - PUID=$UID
      - PGID=$GID
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - USER=username #optional
      # - PASS=password #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      # - HOST_WHITELIST=dnsname list #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  # TV & Movie indexer API
  prowlarr:
    env_file: .env
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=Africa/Johannesburg
    volumes:
      - ./prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # TV & Movie indexer API (I dont use this any more, can be removed)
  jackett:
    env_file: .env
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=Africa/Johannesburg
      # - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./jackett/config:/config
      - $SHARED_MEDIA_LOCATION:/data
    ports:
      - 9117:9117
    restart: unless-stopped
